# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: 🙋  Usage Questions
    url: https://github.com/mediatoolbox-org/slidemaker/discussions
    about: |
      Use SlideMaker's GitHub Discussions to ask "How do I do X with SlideMaker?".
  - name: 📖  Documentation
    url: https://github.com/mediatoolbox-org/slidemaker
    about: |
      The SlideMaker documentation provides an in depth walkthrough
      of how to use the latest release of SlideMaker.
  - name: 📝  SlideMaker Code of Conduct
    url: https://github.com/mediatoolbox-org/slidemaker/blob/main/CODE_OF_CONDUCT.md
    about: Expectations for how people will interact with each other on SlideMaker's GitHub.
